In [18]:
import numpy as np
#Importamos la función numpy para poder hacer la multiplicación entre las listas
lst = []
#Creamos una lista para el ingreso del código
def digito_verificacion(n):
    lst2=[1,2,3,4,5,6,7,8,9]
    
#definimos lst2 como 1,2,3,...,9 para hacer más simple la operación sin necesidad de usar for
    
    for i in n:
        lst.append(int(i))
    
#Este for hace que los datos ingresados inicialmente se agreguen a la lista "lst"
        
    product = (np.multiply(lst[0:9],lst2[0:9]))
    #Con esta operación tomamos los primeros 9 números de la lista que ingresó el usuario y multiplicamos por
    #la lista que ya definimos "lst2" (1,2,3,...,9)
    #Afuera del paréntesis ponemos "%11" lo cual indica que a cada numero de la lista sacará su mod11 
    #Por cierto, esto se guarda en una nueva lista "product"
    print(product)
    #Aquí imprimimos "product" para verificar los datos de la lista luego de la suma
    
    sumatoria= sum(product[0:9])
    print(sumatoria)
    #
    #La idea de este print es poder verificar el modulo 11 de sumatoria manualmente
    #
    sumatoria = sumatoria%11
    #Sumamos los primeros 9 numeros de numeros de la lista "product" e utilizamos %11 para hallar el modulo11 de sumatoria
    print(sumatoria)
    
user_input = input("Escriba un numero:  ")

digito_verificacion(user_input)
#Con este input hacemos que el usuario digite el código
#Gracias a realizar las operaciones solo con los primeros 9 numeros, no importará la cantidad de digitos que ingrese el usuario

Escriba un numero:  123456789
[ 1  4  9 16 25 36 49 64 81]
285
10


In [19]:
#En caso de que se ingrese una lista menor que 9, nuestro programa no se ejecutará ya que el ejercicio
#nos dice que de un codigo que ingrese el usuario debemos hacer la operación con sus primeros 9 digitos




###Bueno ahora intentemos usarlo introduciendo más de 9 digitos






import numpy as np
#Importamos la función numpy para poder hacer la multiplicación entre las listas
lst = []
#Creamos una lista para el ingreso del código
def digito_verificacion(n):
    lst2=[1,2,3,4,5,6,7,8,9]
    
#definimos lst2 como 1,2,3,...,9 para hacer más simple la operación sin necesidad de usar for
    
    for i in n:
        lst.append(int(i))
#Este for hace que los datos ingresados inicialmente se agreguen a la lista "lst"
        
    product = (np.multiply(lst[0:9],lst2[0:9]))%11
    #Con esta operación tomamos los primeros 9 números de la lista que ingresó el usuario y multiplicamos por
    #la lista que ya definimos "lst2" (1,2,3,...,9)
    #Afuera del paréntesis ponemos "%11" lo cual indica que a cada numero de la lista sacará su mod11 
    #Por cierto, esto se guarda en una nueva lista "product"
    print(product)
    #Aquí imprimimos "product" para verificar los datos de la lista luego de la suma
    sumatoria= sum(product[0:9])
    #Sumamos los primeros 9 numeros de numeros de la lista "product"
    print(sumatoria)
    #
    #La idea de este print es poder verificar el modulo 11 de sumatoria manualmente
    #
    sumatoria = sumatoria%11
    #Sumamos los primeros 9 numeros de numeros de la lista "product" e utilizamos %11 para hallar el modulo11 de sumatoria
    print(sumatoria)
user_input = input("Escriba un numero:  ")
digito_verificacion(user_input)
#Con este input hacemos que el usuario digite el código
#Gracias a realizar las operaciones solo con los primeros 9 numeros, no importará la cantidad de digitos que ingrese el usuario
#
#Nos podemos dar cuenta que la suma de 1+4+9+5+3+3+5+9+4 = 43 y el modulo 11 es = 10
#Por ende, nuestra función toma solo los primeros 9 digitos del código ingresado

Escriba un numero:  123456789219649845498
[1 4 9 5 3 3 5 9 4]
43
10


In [20]:
###ahora intentemoslo con un sólo número pero 9 o más digitos, tomemos como ejemplo el "1"






import numpy as np
#Importamos la función numpy para poder hacer la multiplicación entre las listas
lst = []
#Creamos una lista para el ingreso del código
def digito_verificacion(n):
    lst2=[1,2,3,4,5,6,7,8,9]
    
#definimos lst2 como 1,2,3,...,9 para hacer más simple la operación sin necesidad de usar for
    
    for i in n:
        lst.append(int(i))
#Este for hace que los datos ingresados inicialmente se agreguen a la lista "lst"
        
    product = (np.multiply(lst[0:9],lst2[0:9]))%11
    #Con esta operación tomamos los primeros 9 números de la lista que ingresó el usuario y multiplicamos por
    #la lista que ya definimos que era 
    #Afuera del paréntesis ponemos "%11" lo cual indica que a cada numero de la lista sacará su mod11 
    #Por cierto, esto se guarda en una nueva lista "product"
    print(product)
    #Aquí imprimimos "product" para verificar los datos de la lista luego de la suma
    sumatoria= sum(product[0:9])
    #Sumamos los primeros 9 numeros de numeros de la lista "product"
    print(sumatoria)
    sumatoria = sumatoria%11
    print(sumatoria)
    
user_input = input("Escriba un numero:  ")
digito_verificacion(user_input)
#Con este input hacemos que el usuario digite el código
#Gracias a realizar las operaciones solo con los primeros 9 numeros, no importará la cantidad de digitos que ingrese el usuario
#Efectivamente, la suma de 1+2+3+4+5+6+7+8+9 = 45 y su modulo 11 es "1"

Escriba un numero:  111111111111111111111111111
[1 2 3 4 5 6 7 8 9]
45
1
